# == Classic ==
# This is a shorthand to override some of the options to be backwards compatible
# with `ls`. It affects the "color"->"when", "sorting"->"dir-grouping", "date"
# and "icons"->"when" options.
# Possible values: false, true
classic: false

# == Blocks ==
# This specifies the columns and their order when using the long and the tree
# layout.
# Possible values: permission, user, group, size, size_value, date, name, inode
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

# == Color ==
# This has various color options. (Will be expanded in the future.)
color:
  # Possible values: never, auto, always
  when: auto
  theme: default

# == Date ==
# This specifies the date format for the date column. The freeform format
# accepts an strftime like string.
# When "classic" is set, this is set to "date".
# Possible values: date, relative, '+<date_format>'
# `date_format` will be a `strftime` formatted value. e.g. `date: '+%d %b %y %X'` will give you a date like this: 17 Jun 21 20:14:55
date: date

# == Dereference ==
# Possible values: false, true
dereference: false

# == Display ==
# Possible values: all, almost-all, directory-only
# display: all

# == Icons ==
icons:
  # Possible values: always, auto, never
  when: auto
  # Possible values: fancy, unicode
  theme: fancy
  separator: " "

# == Ignore Globs ==
# A list of globs to ignore when listing.
# ignore-globs:
#   - .git

# == Indicators ==
# Possible values: false, true
indicators: false

# == Layout ==
# Possible values: grid, tree, oneline
layout: grid

# == Recursion ==
recursion:
  # Possible values: false, true
  enabled: false
  depth: 3

# == Size ==
# Possible values: default, short, bytes
size: default

# == Permission ==
# Possible value: rwx, octal
permission: rwx

# == Sorting ==
sorting:
  # Possible values: extension, name, time, size, version
  column: name
  # Possible values: false, true
  reverse: false
  # Possible values: first, last, none
  dir-grouping: none

# == No Symlink ==
# Possible values: false, true
no-symlink: false

# == Total size ==
# Possible values: false, true
total-size: false

# == Hyperlink ==
# Possible values: always, auto, never
hyperlink: never

# == Symlink arrow ==
# Specifies how the symlink arrow display, chars in both ascii and utf8
symlink-arrow: ⇒

# == Header ==
# Possible values: false, true
header: false